export const GET_USER_REPOS = "GET_USER_REPOS"
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const SET_API_KEY = "SET_API_KEY"
export const GET_ISSUES = "GET_ISSUES"
export const SET_ISSUES_BOOL = "SET_ISSUES_BOOL"
